### ISSUE TITLE
chore: License Compliance

### ISSUE THREAD

**Issue by kanenorman** [philip-ndikum/TemporalScope#14]
**Ensure License Compliance Using Apache SkyWalking Eyes**

**Description:**

We need to ensure that our project adheres to proper license compliance. To achieve this, the following tasks should be completed:

1. Use [Apache SkyWalking Eyes](https://github.com/apache/skywalking-eyes) to ensure that all source files contain the correct license headers.
2. Verify that all dependencies have appropriate license permissions.
3. Configure CI to automatically check for and fix any license compliance issues.

**Comment by philip-ndikum** [comment]
Thank you very much! Will add this to the latest push. Much appreciated.
