### ISSUE TITLE
[Bug: CI/CD] ReadTheDocs Sync, Missing License Validation, and README Syncing

### ISSUE THREAD

**Issue by philip-ndikum** [philip-ndikum/TemporalScope#47]
### **Describe the Bug**  
Three CI/CD issues are identified for TemporalScope:  

1. **ReadTheDocs Documentation Not Syncing**: Changes to the repository are not reflected in the ReadTheDocs build, resulting in outdated documentation.  
2. **Missing License Validation**: The license bot does not verify the presence of a `LICENSE` file, allowing unlicensed code to pass checks.  
3. **README Syncing**: The README file in a sub-directory of the repository does not sync during CI/CD. Additionally, assets (e.g., images from the `assets/` directory) are not properly copied, causing potential rendering issues or outdated README content.  

---

#### Issue 1: ReadTheDocs Sync Failure  
1. Make changes to the documentation in the repository.  
2. Push the changes to the main branch.  
3. Visit the [[ReadTheDocs page](https://temporalscope.readthedocs.io/en/latest/)](https://temporalscope.readthedocs.io/en/latest/).  
4. Notice the documentation does not reflect the latest updates.  

#### Issue 2: Missing License Validation  
1. Create or modify a branch without a `LICENSE` file.  
2. Push the branch and run the CI pipeline.  
3. Observe that the pipeline passes without flagging the missing `LICENSE` file.  

#### Issue 3: README Syncing  
1. Update the README file in a sub-directory of the repository.  
2. Push the changes to the main branch.  
3. Check the README during or after the CI/CD pipeline run and observe that the content and associated assets are not properly synced or rendered.  

---

### **Expected Behavior**  

1. **ReadTheDocs**: Automatically update the online documentation with the latest changes from the repository.  
2. **License Bot**: Validate the presence of a `LICENSE` file and fail if it is absent.  
3. **README Syncing**: Ensure the README file in the sub-directory syncs correctly during the CI/CD process, including copying all necessary assets from the `assets/` directory.  

---

### **Additional Context**  
- The lack of README syncing can lead to inconsistencies between the local repository and what users see post-CI/CD.  
- Proper asset management for README ensures images and other linked resources are functional and up-to-date.

**Comment by kanenorman** [comment]
Closing in favor of creating separate issues. See #52 , #53 , #54
